### PR TITLE
Changed Font Size of Input boxes in add lobby page

### PR DESCRIPTION
**Pull request by Solai-Adithya**
The placeholders and input text's font size was very small earlier. Now , I have made a minor change in CSS code to increase a font size to a noticeable size.

### CODE REVIEW

**Comment by Solai-Adithya** [comment]
Before: 
before

After :
after_1
after_2

**Comment by abhigyank** [comment]
@LalitNM The merged commit for this is missing in master, could you check if it got missed in the cleanup?

**Comment by LalitNM** [comment]
Yeah, @abhigyank we lost this commit in clean-up. You merged this and few seconds after I did `force-push`.
I think @Solai-Adithya needs to create a new PR for this commit. Is this fine @Solai-Adithya?

**Comment by Solai-Adithya** [comment]
Yeah, I'll make another PR

**Pull request merged**
