### PR TITLE
Center aligned list of online users.

### PR DESCRIPTION
**Pull request by peakercope**
fixes the #61

### CODE REVIEW

**Comment by LalitNM** [comment]
@peakercope the width of container need to be fixed. You can also change it to `width: 100%` if it looks good.

**Comment by peakercope** [comment]
> @peakercope the width of container need to be fixed. You can also change it to `width: 100%` if it looks good.

done

**Comment by LalitNM** [comment]
Some bugs on this PR:

- Participants container overlaps with messages on all screens-sizes.
Screen Shot 2020-10-03 at 09 43 44

- left bar disappears when clicked on online-users button on large screens.
Screen Shot 2020-10-03 at 09 45 57

@peakercope I could identify these bugs with this PR. Please fix them.

**Comment by peakercope** [comment]
@LalitNM fixed

**Comment by abhigyank** [comment]
@peakercope could you fix your commit history to include only the changes you have made? You can check out git rebase for that, however if you're new to this then it maybe easier to just a create a new PR.

**Pull request closed without merging**
