### PR TITLE
Center aligned list of online users

### PR DESCRIPTION
**Pull request by peakercope**
#67

### CODE REVIEW

**Comment by LalitNM** [comment]
It is not helpful @peakercope, update this as soon as possible. And before creating a PR make sure that the issue is fixed by running the code locally, this is how it must be done.

**Comment by peakercope** [comment]
hello @LalitNM , thank for your comment!
Could you please describe more detailed what is your expected result from this feature?
I made list of users full screen for mobile view as you asked [here](https://github.com/KamandPrompt/baat-cheet/pull/67#issuecomment-703059655)

**Comment by LalitNM** [comment]
Have a look at this screenshot
result

The grey area in this picture should display the information about online users.

And for mobile-view the following picture can help you.
res

**Comment by peakercope** [comment]
Got it, you want full with list of uses both for mobile and desktop views
I'll change it in a short

**Comment by peakercope** [comment]
Now it will look like that
image
image

**Comment by LalitNM** [comment]
One more feature one would like to have is that, when someone clicks outside online-user-list, then the list should collapse. For example if somebody directly wants to start typing, now it closes with only the button. Also fix the height of this list, maybe you can make it `50vh`. Any suggestions @abhigyank.

**Comment by LalitNM** [comment]
closing in favor of fa4c0c369d52be122dd1cc649cb93c3aee099510

**Pull request closed without merging**
