### PR TITLE
Added responsive model implementation with simpler sliding sidebar code

### PR DESCRIPTION
**Pull request by isNan909**
I have fixed the necessary changes and I am up to date with the current master. Also I have refactored the slide sidebar to simpler code and responsiveness of bootstrap modal.

### CODE REVIEW

**Comment by LalitNM** [comment]
@ishan-me the problem is not solved, maybe you can use a simpler way to delete your fork and then start working on this.

**Comment by isNan909** [comment]
@LalitNM I still wonder the task was to make a responsive modal and a working sidebar. I have addressed both the issue. Can you specify me the problem please?

**Comment by LalitNM** [comment]
You have to see the files changed in this PR, the only thing which is changed is the left-bar-toggle button's JS code, and now sidebar is not working here. And another thing you have to do is clean your git history, there are still some commits which are already there in our master branch, this is what I meant

**Comment by LalitNM** [comment]
Closing due to inactivity, if you still want to contribute then please make a new PR.

**Pull request closed without merging**
