### PR TITLE
feat(date format): Update date format in message; timestamp near user…

### PR DESCRIPTION
**Pull request by pancreaflame**
for issue #150 

- Support showing only time when the message was sent today, while keep show month and day for the others. All the timestamps will be updated when a new message incomes.
- Move timestamp to same line after username.

### CODE REVIEW

**Comment by LalitNM** [comment]
Everything looks good, but I can't understand why do we need to update time stamp of every message again and again. Can you please explain this.

**Comment by pancreaflame** [comment]
It is necessary to update timestamp every time because the new message is probably sent on today, it has no month and day displayed.
After certain time, the chat room enters the next day. If the timestamp of old messages are not updated, then they will keep having no month and day.

Perhaps we can modify the test a bit, so that those timestamp already have month and day won't be updated the innerHTML any more.

**Comment by pancreaflame** [comment]
Hi @LalitNM , I included #148 , and work on #150 base on that.

Now the strategy is only update the date time without month and day. Once it is updated and add back month and day, `message-today` class will be removed, such that it will not be included the next checking.

The checking is check the sent timestamp against current timestamp. Since I assume the new message is sent on today (initially without month and day), the update of innerText should only occur when the day changes.

**Comment by sesamechicken** [comment]
> The checking is check the sent timestamp against current timestamp. Since I assume the new message is sent on today (initially without month and day), the update of innerText should only occur when the day changes.

I think the important thing to remember here is that with sockets, the data is not persistent. For example, if your client leaves and then returns, the previous data is not magically available to them. They won't see previously sent messages. You could format this really easily with `date-fns` since it's already brought in. The `formatDistance` method seems the most appropriate for an app like this, I think.
 https://date-fns.org/v2.16.1/docs/formatDistance

**Comment by pancreaflame** [comment]
Thanks for reply.
I agree the data is not persistent. So showing "month day hour:minute" should be a rare case.

I observe that gitter is showing "hour:minutes" for today's message, and showing "month day hour:minute" for the rest. Do you mean we are going to use `formatDistance` / `distanceInWords` (for version 1.30.1) for all the message would be fine?

update: just find `formatDistance` / `distanceInWords` take two timestamps. Both sent time and current time. It looks this requires an interval to update?

**Comment by sesamechicken** [comment]
Good point. This isn't my baby, @LalitNM can chime in, but if it were mine, I'd leave the timestamp as is and just use the `format` function.

**Comment by LalitNM** [comment]
@sesamechicken I agree that it is rare that two people use this app at the stroke of the midnight hour. But the problem comes when people use this across timezones. In this situation the timestamp should be updated.

And @pancreaflame you are updating timestamp of previous messages only when some messages is recieved by the user, but it is possible that no message is recieved and the user is just reading previous messages, don't you think that timestamp should be updated? My suggestion would be to constantly update the timestamp of all messages and use `formatDistance`.

**Comment by sesamechicken** [comment]
> @sesamechicken I agree that it is rare that two people use this app at the stroke of the midnight hour. But the problem comes when people use this across timezones. In this situation the timestamp should be updated.

No matter which formatting choice you go with, the times will always be displayed in the users' own time zone. I don't think time zones have anything to do with date/time formatting, tbh.

**Comment by pancreaflame** [comment]
@LalitNM Got it. Then I switch to :

- doing the checking and updates at certain interval, say every 1 minute using `setInterval()`. 
- applying `formatDistance` to all the timestamp, no matter it is sent today or not

**Comment by pancreaflame** [comment]
Hello @LalitNM and @sesamechicken . I have a new commit that the date time will be updated at 1 minute interval and I use date-fns `formatDistance` function to display them.

**Comment by abhigyank** [comment]
> doing the checking and updates at certain interval, say every 1 minute using setInterval().

Don't do this, it adds a lot of unnecessary processing weight on the browser tab for a not so important feature. Avoid running such cron process from frontend.

**Comment by pancreaflame** [comment]
@abhigyank I see your point.

@LalitNM and @sesamechicken , looks like we need to have a trade-off between:
1. To use `formatDistance` offered by date-fns at the cost of processing weight on the browser tab.
2. To show the local date time, using date-fns `format` and update when the day changes.

I see that issue #150 mentioned that, this could be referencing to `gitter` web app. Perhaps we could have a look on that again?

**Comment by abhigyank** [comment]
@pancreaflame you could try setting `setTimeout` till 12am at midnight and then call your function to update time.

**Comment by pancreaflame** [comment]
> @pancreaflame you could try setting `setTimeout` till 12am at midnight and then call your function to update time.

@abhigyank Do you mean setting `setTimeout` for each new message with the delay time is the difference between the sent time and 12am midnight?

eg: Let the sent time is Oct 21 22:45, then run `setTimeout(updateFunc, 75 * 60 * 1000)` when the socket.io send the message to client

To me, I think using one `setInterval()` for one browser tab at one minute interval shouldn't cost such a lot processing weight. But we may even think about put these into Worker flow, if it becomes a matter of performance.

On the other hand, like @sesamechicken mentioned, showing the sent time at users' timezone should be simple enough. The subject matter that @LalitNM mentioned in the #150 issue, is wanting to show sent time without month and day for the message sent on today.

I was putting the update when new message comes, and LalitNM thinks it is not enough. If we wish it updates automatically, using `setInterval()` would be inevitable as for as I know.

**Comment by abhigyank** [comment]
> Do you mean setting setTimeout for each new message with the delay time is the difference between the sent time and 12am midnight

@pancreaflame Yes, but not for every message. You set the setTimeout at the beginning when the webpage is loaded and when it is 12am, the updateTimestamp function just iterates over all the messages and updates. This is independent of any message coming in.

> To me, I think using one setInterval() for one browser tab at one minute interval shouldn't cost such a lot processing weight.

This is just bad design. You want something to be done once at a particular time. Instead you're doing it 24*60 times a day, that is just needless computation and would never scale.

**Comment by abhigyank** [comment]
P.S. We are going for a gitter like design right? gitter is showing "hour:minutes" for today's message, and showing "month day hour:minute" for the rest.

**Comment by pancreaflame** [comment]
@abhigyank Thanks for clarification. I have a new commit implementing that. You may review it.

**Comment by LalitNM** [comment]
This looks great @pancreaflame :clap: Merging this :fireworks:

**Pull request merged**
