### PR TITLE
SHOW ONLINE USERS

### PR DESCRIPTION
**Pull request by rs4231199**
Now one can click on user-count(under the room name) to see names of online users.

image

### CODE REVIEW

**Comment by rs4231199** [comment]
@abhigyank Please review the changes.

**Comment by abhigyank** [comment]
Works fine. Pushed a minor commit.
Merged, good work @rs4231199 :rocket:

**Comment by abhigyank** [comment]
@rs4231199 I had to unmerge this PR #56 . I tested adding of rooms, that breaks if I merge this PR. Can you check? Something is wrong in the added css probably.

**Comment by rs4231199** [comment]
I created multiple rooms and tested them by sharing multiple messages. It worked fine for me.
Can you share the steps to reproduce the behavior?

**Comment by abhigyank** [comment]
Weird, unable to reproduce now. I will try merging it again.

**Pull request merged**
