### PR TITLE
adding responsive screen-overlay

### PR DESCRIPTION
**Pull request by kushal-khare-official**
resolving issue #74 added responsive screen overlay using bootstrap 4

### CODE REVIEW

**Comment by abhigyank** [comment]
@kushal-khare-official Can you remove the unnecessary indentation and refactoring changes in the files?

**Comment by kushal-khare-official** [comment]
@abhigyank I have removed all unnecessary indentation.

**Comment by abhigyank** [comment]
@kushal-khare-official I meant the refactoring changes in index.ejs and the single-double quote change in the CSS file.

Also I think you may have to create a new PR with your changes, because this PR including some commits already in the master.

**Comment by LalitNM** [comment]
Closing due to conflicts and inactivity, If you still want to contribute then please make a new PR.

**Pull request closed without merging**
