### PR TITLE
Refactored the code

### PR DESCRIPTION
**Pull request by DEEPA-CHERI**
- Removed couple of forloops
  - Refactored emoji.js

### CODE REVIEW

**Comment by LalitNM** [comment]
@DEEPA-CHERI, there are still a few places where we are not using `document.getElementByID()` to select the textarea. Can you update those also, and please resolve conflicts by rebasing your local branch with `KamandPrompt: master`.

**Comment by LalitNM** [comment]
@DEEPA-CHERI you need to rebase your branch.

**Comment by DEEPA-CHERI** [comment]
Sure, Will do that.

**Comment by DEEPA-CHERI** [comment]
I have removed the id that I have introduced for the textarea element and reverted the code because When the user is switching between multiple rooms all the rooms context is still present in the dom. Id concept will not work here. My branch is updated now. You could verify now. Thanks.

**Review by LalitNM — APPROVED** [review]

**Comment by LalitNM** [comment]
This looks good @DEEPA-CHERI :clap:

**Pull request merged**
