### PR TITLE
fixed emoji issue, now emojies are working.

### PR DESCRIPTION
**Pull request by LalitNM**

### CODE REVIEW

**Comment by LalitNM** [comment]
@abhigyank, I fixed #28. Have a look.

**Comment by abhigyank** [comment]
@LalitNM Can you show a screenshot of how its looking now? I feel you have removed all emojis :worried:

**Comment by LalitNM** [comment]
Actually I am using UTF-8 characters as emojis.😅
Have a look at this GIF

recording

**Comment by LalitNM** [comment]
Closing this PR, because I used UTF-8 Characters, and all browsers interpret these characters in a different way.

**Pull request closed without merging**
