### PR TITLE
Adds before onunload event listener to warn before closing window or tab

### LINKED ISSUE #123: Show notification that 'All mesaages will be deleted with closing this tab.'
At present there is no log out button, a user has to close tab when he/she wants to leave the app. Add a log out button.

### PR DESCRIPTION
**Pull request by sesamechicken**
Closes https://github.com/KamandPrompt/baat-cheet/issues/123

### CODE REVIEW

**Comment by abhigyank** [comment]
@sesamechicken @LalitNM Should we put this warning in a welcome message from the welcome bot itself? It may get annoying to constantly see a warning when you close the tab.

**Comment by LalitNM** [comment]
Yeah, @sesamechicken, the plan was to add a notification(can be a BS-toast) when somebody just enters the Lobby.

**Comment by sesamechicken** [comment]
> @sesamechicken @LalitNM Should we put this warning in a welcome message from the welcome bot itself? It may get annoying to constantly see a warning when you close the tab.

This makes no sense. If they're leaving the site, they won't see a message in the app.

>Yeah, @sesamechicken, the plan was to add a notification(can be a BS-toast) when somebody just enters the Lobby.

Are we talking about the same issue?

**Comment by LalitNM** [comment]
Yes @sesamechicken, perhaps you missed [this](https://github.com/KamandPrompt/baat-cheet/issues/123#issuecomment-707937552).

**Comment by abhigyank** [comment]
> If they're leaving the site, they won't see a message in the app.

Not while leaving, but rather at the beginning itself when they join. Because an alert everytime you want to quit would be annoying.

Not in favour of a toast/notification, because as @sesamechicken rightly said, when you're leaving you won't look at a notification, it'd just close (unless you want them to say yes or no then, which would be annoying if repeated).

**Pull request closed without merging**
