### PR TITLE
added emojis

### PR DESCRIPTION
**Pull request by sakshi-choudhary**

### CODE REVIEW

**Review by LalitNM — CHANGES_REQUESTED** [review]
changes to be done

- do not stage `package-lock.json` as it is just an installation file.

- please add all emojis from the link given in #89(only yellow ones).

- one more problem with emojify.js is that  it has very long lines. Please limit length of a line to 250 characters.

**Comment by LalitNM** [comment]
Any update @sakshi-choudhary?

**Comment by MonarthS** [comment]
@LalitNM If this is not active, I can replace emojis with the yellow one.

**Comment by LalitNM** [comment]
Closing this due to inactiity.

**Pull request closed without merging**
