### PR TITLE
Added Confirmation when reloading or closing the tab

### PR DESCRIPTION
**Pull request by Gautam-Arora24**
Screenshot 2020-10-14 at 2 26 49 PM

Added confirmation overlay when a user tries to reload or closes the tab

### CODE REVIEW

**Comment by LalitNM** [comment]
Your commits changed almost everything in the code, which is not acceptable. You are supposed to add only those changes which you need in order to fix the issue. You have to delete all these unnecessary formatting changes. This is the reason for all these conflicts. You also have to rebase  your branch with upstream(see contribution guidelines). In addition to this you are not supposed to add `package-lock.json` in your commit.

Now comes the issue part. You are showing a message when someone tries to leave the application. This is not what I asked you to do in #123. I told you to add a toast when somebody enters the application saying that 'All messages will be deleted once you close this tab'.

You might want to reset your branch to the previous version, then you can read about this.

PS Git skills are very important in order to contribute to any repository on github. You have to learn all these if you want to contribute to opensource.

**Comment by Gautam-Arora24** [comment]
There is no shame for hardwork. I will work on this :-)

**Comment by LalitNM** [comment]
If you need any help from me, you can ask me on gitter. Link is in readme.

**Comment by Gautam-Arora24** [comment]
Sure

**Comment by abhigyank** [comment]
Closing on favour of #154

**Pull request closed without merging**
