### PR TITLE
Show notification if new message comes to any room

### LINKED ISSUE #24: Show notification if new message comes to any room

### PR DESCRIPTION
**Pull request by MonarthS**
Fix #24

### CODE REVIEW

**Comment by MonarthS** [comment]
@LalitNM can you check this?

**Review by abhigyank — COMMENTED** [review]
The approach looks correct, some changes to code-flow would be required, But we wouldn't be able to test this until we close #64 . So let's wait till that is solved before moving on with this PR.

**Comment by MonarthS** [comment]
Already in progress #88. May be tomorrow we can go on this.

**Comment by LalitNM** [comment]
Merged :rocket:

**Pull request merged**
