### PR TITLE
Hotfix/input custom room

### PR DESCRIPTION
**Pull request by laisfrigerio**
Input message event listener with `.textarea` class

### CODE REVIEW

**Comment by laisfrigerio** [comment]
issue @ #64

**Comment by abhigyank** [comment]
@laisfrigerio can you clean up you commit history to one commit that includes the changes you want to do for this fix?

**Comment by laisfrigerio** [comment]
@abhigyank  Is okay now?

I used `git rebase` to squash commits

**Comment by abhigyank** [comment]
@laisfrigerio For some reason the PR has 21 commits to merge, some of which are already in the mastee.while I suppose, this can be fixed using git tool, one easier way would be to sync your fork copy with the latest master, make your changes and make a new PR. That way it would be easier for you I think.

**Comment by laisfrigerio** [comment]
@abhigyank I make a fork yesterday and today I update my fork because the master was ahead from my fork. Thats why my pull request has 21 commits.

**Comment by laisfrigerio** [comment]
@abhigyank  I will make a new fork and pull request

**Comment by laisfrigerio** [comment]
@abhigyank  Can I close this pull request? I will make a new one

**Comment by abhigyank** [comment]
Yes go ahead @laisfrigerio

**Pull request closed without merging**
