### PR TITLE
Message Input bar not visible in Rooms

### PR DESCRIPTION
**Pull request by laisfrigerio**
Issue #64 

Only one commit ;)

### CODE REVIEW

**Comment by LalitNM** [comment]
@laisfrigerio one commit is good, but there are some bugs this PR creates

1. emojis not working in new room.
steps to reproduce: open a new room and click emoji icon.

2. List of online user is not there in second room.
steps to reproduce: click on `online user list` in second room.
Error in console is `Uncaught TypeError: room is not a constructor`.

3. Leftbar collapses even on large screens when clicked outside it
steps to reproduce: add a new room > resize the window(so that the leftbar collapses) > expand the leftbar > restore original size of window > click outside leftbar.

In addition to these bugs also remove timestamp at the beginning of conversation as there is already timestamp on every message.

**Comment by laisfrigerio** [comment]
Hello, @LalitNM 

About item 3: I couldn't reproduce this error on my branch following your steps.

Itens 1 and 2: I will check it

**Comment by LalitNM** [comment]
Leave it for now, I think it has been fixed in #91, resolve the conflicts also

**Comment by laisfrigerio** [comment]
@LalitNM  Hello, I fix item 1 and 2.

About conflicts: In my branch, the file `views/index.ejs` has a div with a class `.container`. 
In master the class changed. Is `.app-container`.

If change this info here (my branch), You cannot test

**Comment by LalitNM** [comment]
I saw the logs of your branch. It lacks [this](https://github.com/KamandPrompt/baat-cheet/commit/9c02b7933aaaea70320aba868c0bfc29b1623b0b) commit which is there in our master branch, you have to rebase your local branch to `KamandPrompt: master`, resolving conflicts will not be enough.

What best I can suggest is

- remove all commits made by you using `git reset -hard HEAD~<no. of commits you want to remove>`(here you need to remove 2 commits).

- add upstream to your remote repository using `git remote add https://github.com/KamandPrompt/baat-cheet/`

- fetch upstream using `git fetch upstream`

- rebase to upstream using `git rebase upstream/master`

- add commits

- force push to this branch using `git push -f origin master`

In addition to this remove `package-lock.json` from commits(avoid using `git add .`) and remove tthe timestamp at the start of conversation.

MOST IMPORTANT: read about all these commands.

**Comment by laisfrigerio** [comment]
@LalitNM merge Ok!!!

Could you check if everything is okay now??

**Comment by LalitNM** [comment]
Merged :rocket: Good work @laisfrigerio.

**Comment by laisfrigerio** [comment]
Thanks, @LalitNM

**Pull request merged**
