### PR TITLE
Emoji

### PR DESCRIPTION
**Pull request by harshitmittal99**
Emojis are working now

### CODE REVIEW

**Comment by LalitNM** [comment]
@harshitmittal99 maybe you should see #47.

**Comment by harshitmittal99** [comment]
thanks lalit, I will update the pr.

**Comment by abhigyank** [comment]
My suggestion is to use https://github.com/iamcal/js-emoji . and [jsDeliver](https://www.jsdelivr.com/?query=emoji-datasource%20author%3A%20iamcal) for the emoji images.

If you look into the code of js-emoji, you will see it is setting paths of the images and sheets, so for it  the code would be something like this - 
```js
for (var i in emoji.img_sets){
	emoji.img_sets[i].path = 'https://cdn.jsdelivr.net/npm/emoji-datasource-' + i + '@5.0.1/img/' + i + '/64/';
	emoji.img_sets[i].sheet = 'https://cdn.jsdelivr.net/npm/emoji-datasource-' + i + '@5.0.1/img/' + i +'/sheets/64.png';
}
```

**Comment by abhigyank** [comment]
Closing in favour of #50.

**Pull request closed without merging**
