### PR TITLE
Some changes are made to username written under each message.

### PR DESCRIPTION
**Pull request by rs4231199**
Two properties are added to  .container .right .bubble .info
  ( float:right; , color: rgba(1,1,1,0.35); )

### CODE REVIEW

**Comment by abhigyank** [comment]
What does the change fix? Cab you put a before and after screenshot? @rs4231199

**Comment by rs4231199** [comment]
before

after

Before: username was on the left-hand side and as dark as the message.
After: username is on the right-hand side and little lighter in color.

**Comment by abhigyank** [comment]
Does the starting message also move to top now?

**Comment by rs4231199** [comment]
At bottom starting message was overlapping with sending bar. So I thought it would be better to move it to the top.

**Comment by abhigyank** [comment]
> At bottom starting message was overlapping with sending bar.
We can put some margin between then probably. It is not good to move the starting message to the top, as chat app starts messaging from bottom. Can you change that?

**Comment by rs4231199** [comment]
Okay

**Comment by rs4231199** [comment]
Screenshot from 2019-06-21 14-36-47

**Comment by abhigyank** [comment]
Merged. Thanks @rs4231199 , good work! 🚀

**Pull request merged**
